image:
  - Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python39"
    - PYTHON: "C:\\Python39-x64"
    - PYTHON: "C:\\Python310"
    - PYTHON: "C:\\Python310-x64"
    - PYTHON: "C:\\Python311"
    - PYTHON: "C:\\Python311-x64"

install:
  - "%PYTHON%\\python.exe -m pip install wheel ."

build: false

test_script:
  - "%PYTHON%\\python.exe test.py"

after_test:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*
